### ISSUE TITLE
Reporting plugin puppeteer failed to launch chrome

### ISSUE THREAD

**Issue by csandanov** [wodby/kibana#2]
```
{"type":"log","@timestamp":"2020-06-08T13:48:24Z","tags":["error","reporting"],"pid":1,"message":"Error: Failed to launch chrome! spawn /usr/share/kibana/data/headless_shell-linux/headless_shell ENOENT\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\n    at onClose (/usr/share/kibana/node_modules/puppeteer-core/lib/Launcher.js:349:14)\n    at ChildProcess.helper.addEventListener.error (/usr/share/kibana/node_modules/puppeteer-core/lib/Launcher.js:340:64)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"type":"log","@timestamp":"2020-06-08T13:48:24Z","tags":["warning","reporting"],"pid":1,"message":"See Chromium's log output at \"/usr/share/kibana/data/headless_shell-linux/chrome_debug.log\""}
{"type":"log","@timestamp":"2020-06-08T13:48:24Z","tags":["error","reporting"],"pid":1,"message":"Error: Could not close browser client handle!\n    at browserFactory.test.then.browser (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/lib/validate/validate_browser.js:26:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"type":"log","@timestamp":"2020-06-08T13:48:24Z","tags":["warning","reporting"],"pid":1,"message":"Reporting plugin self-check generated a warning: Error: Could not close browser client handle!"}
```

File `/usr/share/kibana/data/headless_shell-linux/chrome_debug.log` does not exist.

**Comment by csandanov** [comment]
https://discuss.elastic.co/t/kibana-reporting-plugin-fails-to-launch-chrome-puppeteer/236195
